theme: jekyll-theme-minimal
title: A Journey Through DS and Algorithms
description: Dive into the world of Data Structures and Algorithms with C++ template references, comprehensive notes, and in-depth problem analysis.

markdown: kramdown
kramdown:
    math_engine: mathjax